### PR TITLE
Add: pyos profile to cookie

### PR DESCRIPTION
**Pull request by lwasser**
## Pull Request description

This is a PR that adds a pyOpenSci profile to the osl cookiecutter!

## How to test these changes

`scicookie --profile pyos`

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [x] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by xmnlab** [comment]
hey @lwasser , thanks for working on that!

I just fixed that issues you pointed me yesterday, and I cut a new release as well.
please, feel free to ping me anytime if you have any question, comment or recommendation :)

**Comment by xmnlab** [comment]
hi @lwasser ! 

just checking if you want to move this PR forward, if you want any help we can jump into a pair-review session and finish that together.

all the best,

**Comment by lwasser** [comment]
oh gosh i forgot about this Ivan. Let's get something scheduled. i've been so busy.

**Comment by xmnlab** [comment]
Hi @lwasser , sure thing! that would be great! sorry for the delay here!

maybe we could schedule a meeting after the pyOS event :)

**Comment by xmnlab** [comment]
hey @lwasser , I am closing this PR. feel free to ping me if you want to move this forward, please!
happy holidays!

**Pull request closed without merging**
