### PR TITLE
imp: identation of the dependencies in the pyproject.toml file for the different build systems

### PR DESCRIPTION
**Pull request by YurelyCamacho**
## Pull Request description

Fixes: #154 

## Pull Request checklists

This PR is a:

- [X] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [ ] New and old tests passed locally.

## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [X] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by xmnlab** [comment]
I just fixed the CI. it seems you now have some git conflict in 2 files,
could you rebase your branch on top of the upstream main, please? thanks

**Comment by YurelyCamacho** [comment]
@xmnlab Can you check it again?

**Comment by YurelyCamacho** [comment]
@xmnlab No, I'm already doing it. It's something with the changes you made yesterday. I'm already working it out. I'll let you know

**Comment by YurelyCamacho** [comment]
@xmnlab For some - that you removed in some jinja statements that remove spaces and that's why the error occurred.

**Comment by xmnlab** [comment]
@YurelyCamacho , sorry, I am not following you.

if you check it here: https://github.com/osl-incubator/scicookie/commits/main/

my PR when was merged, the CI passed
the CI for the next PR with my changes also passed.

so the issue in on your PR, maybe when you rebased the changes from upstream/main it had some issues with the new changes.

**Comment by YurelyCamacho** [comment]
@xmnlab Don't worry, it's because of the conflict that existed (I'm giving a new approach to indentation).

**Comment by YurelyCamacho** [comment]
@xmnlab @Anavelyz If you can take a look at it please.

**Comment by xmnlab** [comment]
thanks @YurelyCamacho , I will play with that locally tomorrow :)

**Comment by YurelyCamacho** [comment]
@xmnlab great, thanks

**Comment by xmnlab** [comment]
that looks great! thanks @YurelyCamacho

**Pull request merged**
