### PR TITLE
perf(template): Improving the git workflow for the template

### PR DESCRIPTION
**Pull request by Anavelyz**
## Pull Request description

* Editing `prepare_git` function in `src/scicookie/hooks/post_gen_project.py`.
* Editing files in `src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/`
* Fix an unnecessary space.
* Adding virtualenv workflow
* Updating guide.md

Solve #38

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:
- [x] it includes tests.
- [x] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist
- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved.

### CODE REVIEW

**Review by xmnlab — COMMENTED** [review]
@Anavelyz could you update/rebase your branch please?

**Comment by xmnlab** [comment]
@Anavelyz thanks for working on that!!
could you rebase your branch please?

about the conda/virtualenv .. that is awesome ... we really to add this support! maybe we could have a quick meeting to discuss a bit more about that, because some backend already implement virtual env under the hood, for example hatch and poetry. I think that if we could keep the ci workflow in just one file, instead of splitting it into different folders it would be better

about the git stuff .. I think your approach is not much more complex (many lines) compared to the current approach ... 
please check if there is anything extra that your PR handle that was not handled by my previous PR and keep it, otherwise I think it would be better to just rollback your changes about the git workflow.
again, really sorry about my last PR that implemented the git stuff ... I messed that up XD it was not my intention ... I just was in a mood to fix a bunch of things ... and I forgot about your PR .. really sorry

**Comment by Anavelyz** [comment]
😃 
@xmnlab thank for your review.

> could you rebase your branch please?

Yes, then I do. I should check your changes carefully, in my approach what I try to do is to check whether or not the URLs entered by the users exist.

> about the conda/virtualenv .. that is awesome ... we really to add this support! maybe we could have a quick meeting to discuss a bit more about that, because some backend already implement virtual env under the hood, for example hatch and poetry. I think that if we could keep the ci workflow in just one file, instead of splitting it into different folders it would be better

👍🏾 
Yes, I agree that a meeting is needed.

> again, really sorry about my last PR that implemented the git stuff ... I messed that up XD it was not my intention ... I just was in a mood to fix a bunch of things ... and I forgot about your PR .. really sorry

Don't worry, It's great to see that there is meaningful input 🥳

**Comment by Anavelyz** [comment]
@xmnlab Can you review it? Thank you!

**Comment by xmnlab** [comment]
@Anavelyz , sorry for taking that much time for reviewing this PR, I was on vacation.
it looks great, thanks for working on that!

**Pull request merged**
