### PR TITLE
docs(update): fixed theme issues and updated mkdocs-jupyter

### LINKED ISSUE #261: Update mkdocs config
- [ ] Update mkdocs-jupyter to 0.24.7
- [ ] Add support for dark/light mode switch toggle

- refs:
  - https://github.com/arxlang/astx/blob/main/mkdocs.yaml#L36-L51
  - https://github.com/arxlang/astx/blob/main/mkdocs.yaml#L107-L114

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**
## Pull Request description

Added dark-light mode toggle switch to documentation and updated mkdocs-jupyter to 0.24.7

Fixes #261 

## How to test these changes
`mkdocs serve`

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more
      complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by Naman-Priyadarshi** [comment]
I changed the accent from `amber` to `lime`, let me know if you want me to change it back

**Comment by xmnlab** [comment]
@Naman-Priyadarshi , looks good to me.

I just fixed the CI. could you rebase your branch on top of the upstream main, please?

**Review by Saransh-cpp — COMMENTED** [review]
Thanks, @Naman-Priyadarshi! This looks good to me overall. Could you please check why the top bar is not changing its colour in dark mode - 

image

**Comment by Naman-Priyadarshi** [comment]
I think not changing the colour of the top bar is in advantage here, as our current (temporary) logo is not visible with a dark background.

**Comment by Saransh-cpp** [comment]
Oh I see, thanks!

**Review by Saransh-cpp — APPROVED** [review]

**Comment by xmnlab** [comment]
thanks @Naman-Priyadarshi for working on that!
thanks @Saransh-cpp for the review!

**Pull request merged**
