### PR TITLE
perf(project information): adding missing information

### PR DESCRIPTION
**Pull request by YurelyCamacho**
## Pull Request description
Adding missing information after the project creation and fix bugs 3/5

  - Description using the one given via TUI in `pyproject.toml`
  - Adding `packages` entry in `pyproject.toml`
  - Fix a block with wrong indentation in the release workflow in the template

Solve #147 

## Pull Request checklists

This PR is a:
- [x] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:
- [ ] it includes tests.
- [x] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by YurelyCamacho** [comment]
@xmnlab In the case of setuptools, I think this needs to be added:  https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

Thanks @Anavelyz for your comment

**Comment by xmnlab** [comment]
> @xmnlab In the case of setuptools, Do you consider it necessary to add this?: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
> 
> Thanks @Anavelyz for your comment

@YurelyCamacho could you give me more details about this?

**Comment by xmnlab** [comment]
@YurelyCamacho in general it looks great! thanks for working on that.
just a question about the following points:

- description is using the default one, instead of the one given via TUI
- authors has the correct email, but the name is the default one, instead of the one given via TUI
- The git user is not set correct (the name used is from the default, instead of the one given via TUI)
 
so basically, what that means is that at the end scicookie is not using the values specified in the inputs .. it uses just the default values .. for example if I type for the name "Luffy" at the end the ouput project will have "Rorona Zoro", instead of Luffy.

if you generate a new project, check the pyproject file and the git history inside the project with `git log`

could you check if that was resolved or if you can still see that issue please?
other than that, everything looks great :) thank you so much

**Comment by xmnlab** [comment]
also, I am totally fine to merge this PR as it is, and you can work on a follow-up to address the other points if anything else is missing.

**Comment by xmnlab** [comment]
oh just saw that you already mentioned about that in your initial comments. 
ok, let's merge the PR. thank you so much

**Pull request merged**
