### PR TITLE
ci(template): update ci configuration for main branch only

### LINKED ISSUE #214: template: The CI should execute just for the main branch
change the first lines of the main.yaml file in the template (https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/main.yaml#L1-L3)

to this:

```yaml
name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
```

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**
## Pull Request description
This pull request updates the CI configuration to ensure that it only executes for the main branch. This change is being made to streamline our CI process and ensure that tests and workflows are only triggered for changes made to the main branch.

Fixes #214 

## How to test these changes

- `...`

## Pull Request checklists

This PR is a:

- [x] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more
      complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by Naman-Priyadarshi** [comment]
Hi @Saransh-cpp , could you help me out here? I need help understanding why the test is failing. The pre-commit hooks were executed successfully yet I'm having a linter error

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @Naman-Priyadarshi! The error is originating from the generated project. You should be able to reproduce it by either running the tests locally or by generating a project with the exact same config and running `pre-commit run -a` inside it.

The error is not related to this PR (I am guessing it is due to the latest `ruff` release) but it would be nice if it can be fixed here itself/

**Review by Saransh-cpp — COMMENTED** [review]
Hi @Naman-Priyadarshi

If you go through the failing logs, at the end you'll see (truncating a lot of information) -
```
-------------------- Smoke test for use_prettier=yes -------------------
+ PATH_ORI=/home/runner/miniconda3/envs/scicookie/bin:/home/runner/miniconda3/condabin:/home/runner/miniconda3/condabin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
++ pwd
+ PWD_ORI=/home/runner/work/scicookie/scicookie
+++ dirname /home/runner/work/scicookie/scicookie/tests/smoke/base.sh
++ cd /home/runner/work/scicookie/scicookie/tests/smoke
++ cd ../..
++ pwd
+ PROJECT_PATH=/home/runner/work/scicookie/scicookie
++ which conda
+ '[' /home/runner/miniconda3/condabin/conda == '' ']'
+ ENV_NAME=osl-python-package
+ OUTPUT_DIR=/tmp/osl
+ rm -rf /tmp/osl
+ mkdir -p /tmp/osl
+ cookieninja --no-input --output-dir /tmp/osl /home/runner/work/scicookie/scicookie/src/scicookie use_prettier=yes
Initialized empty Git repository in /tmp/osl/osl-python-package/.git/
...
...
+ cd /tmp/osl/osl-python-package
+ set +x
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache


Looking for: ["python[version='>=3.8.1,<4']", 'pip', 'poetry', 'nodejs']


Transaction

  Prefix: /home/runner/miniconda3/envs/osl-python-package

  Updating specs:

   - python[version='>=3.8.1,<4']
   - pip
   - poetry
   - nodejs


  Package                         Version  Build                Channel           Size
────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────

  + python_abi                       3.12  4_cp312              conda-forge     Cached
...
...
────────────────────────────────────────────────────────────────────────────────────────
...
...
++ echo /home/runner/miniconda3/envs/osl-python-package/bin:/home/runner/miniconda3/condabin:/home/runner/miniconda3/condabin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
++ sed -E 's/[^:]+\/scicookie\/[^:]+//g'
+ export PATH=/home/runner/miniconda3/envs/osl-python-package/bin:/home/runner/miniconda3/condabin:/home/runner/miniconda3/condabin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
+ PATH=/home/runner/miniconda3/envs/osl-python-package/bin:/home/runner/miniconda3/condabin:/home/runner/miniconda3/condabin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
+ command -v poetry
+ poetry install
Updating dependencies
Resolving dependencies...
...
...
+ command -v makim
+ makim tests.linter
...
...
fix end of files.........................................................Passed
- hook id: end-of-file-fixer
- duration: 0.04s
prettier.................................................................Failed
- hook id: prettier
- duration: 0.47s
- files were modified by this hook

.github/workflows/main.yaml

check-python.............................................................Passed
- hook id: check-python
- duration: 0s

Python 3.12.2

black....................................................................Passed
- hook id: black
- duration: 0.24s

All done! ✨ 🍰 ✨
4 files left unchanged.

ruff.....................................................................Passed
- hook id: ruff
- duration: 0.01s

warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.

Traceback (most recent call last):
  File "/tmp/tmp411czlw1.makim", line 2, in <module>
    pre-commit run --all-files --verbose
Makim Error #1: /home/runner/miniconda3/envs/osl-python-package/bin/xonsh 
/tmp/tmp411czlw1.makim
```

See how the smoke tests are failing whenever the generated project is using `prettier`, `pre-commit`, and `poetry`. The tests are not failing for scicookie, but they are failing for the project generated using scicookie, we test both the things. I generally like to create a new project with scicookie enabling these options and run `pre-commit` inside the folder to see the failing changes. I did the same this time and it edited the code generated from the following snippet -

https://github.com/osl-incubator/scicookie/blob/1b1db90358d11c97d02fa7462bfcb1ef6b6b786c/src/scicookie/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/main.yaml#L28-L32

to -

```diff
diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
index 2b07457..9c2afc4 100644
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -17,10 +17,9 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-
       - uses: actions/checkout@v3
         with:
-          python-version : "pypy3.9"
+          python-version: "pypy3.9"
 
       - name: Create virtual environment
         run: source osl-python-package/bin/activate
```

Therefore, updating the above code with -

```yaml
{% else %}
      - uses: actions/checkout@v3
        with:
          python-version: "pypy3.9"
```
should theoretically work.

Alternatively, you can run these tests locally, or read the configuration of the tests in the bash files and reproduce them on your own. I hope this helps!

**Comment by Naman-Priyadarshi** [comment]
> See how the smoke tests are failing whenever the generated project is using `prettier`, `pre-commit`, and `poetry`. The tests are not failing for scicookie, but they are failing for the project generated using scicookie, we test both the things. I generally like to create a new project with scicookie enabling these options and run `pre-commit` inside the folder to see the failing changes. I did the same this time and it edited the code generated from the following snippet -

> Alternatively, you can run these tests locally, or read the configuration of the tests in the bash files and reproduce them on your own. I hope this helps!

Thanks, @Saransh-cpp. I was able to reproduce the error by creating a new project with default settings and using poetry, pre-commit, and prettier. This led to using pre-commit run --all-files to identify the required linter changes.

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @Naman-Priyadarshi! This looks good now!

**Pull request merged**
