### PR TITLE
docs(upgrade): add section in contributing guide and new installation page

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**
## Pull Request description

Added a new page for installation and a section for documentation development in `contributing.md`.

A small step towards #191 
## How to test these changes

- `...`

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more
      complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]
This looks good, thanks @Naman-Priyadarshi!

**Comment by Naman-Priyadarshi** [comment]
@Saransh-cpp I was wondering if I should add a new page for code of conduct, let me know your opinions on it.

**Comment by Saransh-cpp** [comment]
Yes, but maybe in another PR?

**Comment by Naman-Priyadarshi** [comment]
Yeah sure, I'll open a new PR after this is merged.

**Pull request merged**
