### PR TITLE
chore(ci): Update CI workflow

### PR DESCRIPTION
**Pull request by xmnlab**
## How to test these changes

* ```...```

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by xmnlab** [comment]
@Saransh-cpp , this was the issue: https://github.com/psf/black/pull/3932

hope to have ruff as default soon, instead of black XD

**Comment by xmnlab** [comment]
@Saransh-cpp , sorry for changing too much in this PR.
but I think it is necessary to have that sooner than later
also I fixed some small issues

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @xmnlab! This looks great!

I also noticed that a lot of fields in `base.yaml` are set to `visible: false`. Was there a reason for it? For instance, fields like `project_layout`, `build_system`, ..., should be visible in the CLI but they're not. Could you make them visible in this PR itself?

**Comment by xmnlab** [comment]
@Saransh-cpp , good catch!
you're right, it should be available in the base.yaml, and it could be hidden in the profile files

**Pull request merged**
