### PR TITLE
ci(caching): add cache for conda environment in template ci and update ruff linter commands

### LINKED ISSUE #102: Add cache for conda environment on CI (project and template)
Add cache for conda environment on CI for both the main project the template.

ref: https://github.com/elixir-image/image/blob/ea8cf860287877b79615131bac2f08a8565d354e/_.github/workflows/ci.yml#L15

thanks @EverVino for the reference.

### PR DESCRIPTION
**Pull request by Naman-Priyadarshi**
## Pull Request description

Implemented caching for conda environment in template's ci
Fixes #102 

## How to test these changes

- `...`

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [x] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more
      complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Comment by Naman-Priyadarshi** [comment]
Hi @xmnlab, How should I define the matrix.os here? The solution we use in scicookie's ci is 
```
tests:
    strategy:
      matrix:
        os:
          - "ubuntu"
          - "macos"
          - "windows"

    runs-on: ${{ matrix.os }}-latest

    concurrency:
      group: ci-main-tests-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
```

So should we use a similar structure?

**Comment by xmnlab** [comment]
@Naman-Priyadarshi , ping me when this is ready again for review, thanks!

**Comment by Naman-Priyadarshi** [comment]
Hi @xmnlab, I was wondering that maybe you could help me out here? I tired various ways of indentation and also there is a smoke(linter) error, I will display it below:

```
--- a/src/osl_python_package/__init__.py
+++ b/src/osl_python_package/__init__.py
@@ -8,11 +8,11 @@ def get_version() -> str:
     try:
         return importlib_metadata.version(__name__)
     except importlib_metadata.PackageNotFoundError:  # pragma: no cover
-        return "0.1.0"  # semantic-release
+        return '0.1.0'  # semantic-release
 
 
 version = get_version()
 
 __version__ = version
-__author__ = "Roronoa Zoro"
-__email__ = "zoro@one.piece"
+__author__ = 'Roronoa Zoro'
+__email__ = 'zoro@one.piece'
diff --git a/tests/test_main.py b/tests/test_main.py
index 9103361..ba8a824 100644
--- a/tests/test_main.py
+++ b/tests/test_main.py
@@ -1,4 +1,5 @@
 """Tests for osl_python_package package."""
+
 import pytest
 
 from hypothesis import given
 ```

**Comment by xmnlab** [comment]
It seems the error you reported is not related to your implementation. For me it looks like it was created for black option and it is running ruff.

The error I am seem in the logs is related to the empty space control:

https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control

**Comment by xmnlab** [comment]
https://github.com/osl-incubator/scicookie/actions/runs/9851267799/job/27197844485?pr=301

**Comment by xmnlab** [comment]
@Naman-Priyadarshi any progress on this one? any block?

**Comment by Naman-Priyadarshi** [comment]
Haven't really worked with jinja or any templating engine so it's kinda confusing for me, I'll try to read more about it

**Comment by Naman-Priyadarshi** [comment]
Fixed the escape (% raw %) syntax, works fine now! I'll checkout the linter error

**Comment by Naman-Priyadarshi** [comment]
@xmnlab I think this works fine now. Now the format looks like this
```
      - name: Cache Conda Packages
      - uses: actions/cache@v3
        with:
          path: ~/.conda/envs/bla
          key: ubuntu-latest-conda-${{ hashFiles('conda/dev.yaml') }}
          restore-keys: |
            ubuntu-latest-conda-

      - uses: conda-incubator/setup-miniconda@v3
```

**Review by xmnlab — APPROVED** [review]

**Comment by xmnlab** [comment]
Thanks  @Naman-Priyadarshi

**Pull request merged**
