### PR TITLE
fix: Fix support for pipx

### PR DESCRIPTION
**Pull request by xmnlab**
## How to test these changes

- `...`

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved
```

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]
Thank you for the fix, @xmnlab! I can confirm that this is working for me on a macOS machine (I do not have a Windows machine handy right now to test this, however). Your speed with which you looked into this and our correspondence over the past few days is really appreciated.

Edit; adding the reviewer's checklist below:

- [x] I managed to reproduce the problem locally from the `main` branch
- [x] I managed to test the new changes locally
- [x] I confirm that the issues mentioned were fixed/resolved

**Comment by agriyakhetarpal** [comment]
Note: I tested with `pipx install` based on a discussion from this thread: https://github.com/pypa/pipx/issues/812, let me test with `pipx run` as well.

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @xmnlab! This looks good to me!

**Comment by xmnlab** [comment]
thanks @agriyakhetarpal and @Saransh-cpp for the review! appreciate that.

@agriyakhetarpal , I didn't test it with `pipx install`, just with the `pipx run`, so I think we are good to merge this :)
but feel free to ping me if you have any issue!

**Pull request merged**
